version: '3'

services:
  postgres:
    image: postgres:13-alpine
    container_name: ${DB_USER}_postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_USER}pass
      POSTGRES_DB: ${DB_USER}

  postgres_test:
    image: postgres:13-alpine
    container_name: ${DB_USER}_postgres_container_test
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_USER}pass
      POSTGRES_DB: ${DB_USER}test

  pgAdmin:
    image: dpage/pgadmin4
    ports:
      - "8000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  pgvol:
  pgadmin:
