version: '3'

services:
  database_test:
    build:
      context: ./docker/database_test
    environment:
      - MYSQL_DATABASE={DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_USER}_pass
    ports:
      - "3307:3307"
    volumes:
      #- ./docker/database/init.sql:-entrypoint-initdb.d/init.sql
      - ./docker/database_test/data:/var/lib/mysql

  php-fpm:
    build:
      dockerfile: ./docker/php-fpm/Dockerfile
      context: .
    depends_on:
      - database_test
    environment:
      - APP_ENV=test
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL={DATABASE_URL}
    volumes:
      - .:/var/www

  nginx:
    build:
      dockerfile: ./docker/nginx/Dockerfile
      context: .
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"
